import { Player } from '../core/Player';

export const PLAYERS: Player[] = [
    {   id: 1234,
        league_id: 128,
        season_id: 2015,
        team_id: 3148,
        captain: 2,
        injury: 2,
        team_name: "北京国安",
        player_id: 103170,
        name: "杨智",
        known_name: "杨智",
        position: 1,
        name_en: "Yang Zhi",
        known_name_en: "Yang Zhi",
        birth_date: "1983-01-15",
        age: 32,
        first_nationality: "China PR",
        weight: 78,
        height: 186,
        jersey_num: 22,
        real_position: 1,
        real_position_side: 0,
        join_date: "2005-01-01",
        country: "中国",
        preferred_foot: 0,
        worth: 42.5,
        description: "简介",
        image_86x120_url: "http://gdc.hupucdn.com/gdc/soccer/player/photo//86x120/103170.jpg",
        image_130x180_url: "http://gdc.hupucdn.com/gdc/soccer/player/photo//130x180/103170.jpg",
        market_value: 100,
        contract_until: "2015-09-01",
        detailed_position: "{\"main_position\":{\"type\":9},\"side_position\":[{\"type\":11},{\"type\":13}]}"        
    },
    {   id: 1235,
        league_id: 128,
        season_id: 2015,
        team_id: 3148,
        captain: 2,
        injury: 2,
        team_name: "北京国安",
        player_id: 103170,
        name: "杨智",
        known_name: "杨智",
        position: 1,
        name_en: "Yang Zhi",
        known_name_en: "Yang Zhi",
        birth_date: "1983-01-15",
        age: 32,
        first_nationality: "China PR",
        weight: 78,
        height: 186,
        jersey_num: 22,
        real_position: 1,
        real_position_side: 0,
        join_date: "2005-01-01",
        country: "中国",
        preferred_foot: 0,
        worth: 42.5,
        description: null,
        image_86x120_url: "http://gdc.hupucdn.com/gdc/soccer/player/photo//86x120/103170.jpg",
        image_130x180_url: "http://gdc.hupucdn.com/gdc/soccer/player/photo//130x180/103170.jpg",
        market_value: 100,
        contract_until: "20160901",
        detailed_position: "{\"main_position\":{\"type\":9},\"side_position\":[{\"type\":11},{\"type\":13}]}"        
    }
];